services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  publisher:
    build: ./publisher
    container_name: publisher
    ports:
      - "8000:8000"
    depends_on:
      - kafka
  
  subscriber_interesting:
    build: ./subscriber_interesting
    container_name: subscriber_interesting
    ports:
      - "8001:8000"
    depends_on:
      - kafka
      - mongo

  subscriber_not_interesting:
    build: ./subscriber_not_interesting
    container_name: subscriber_not_interesting
    ports:
      - "8002:8000"
    depends_on:
      - kafka
      - mongo